#!/bin/sh

# Gives a dmenu prompt to mount unmounted USB drives
# Uses udisks2 to mount

function rofi_list_drives() {
	local usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"
	if [[ -z $usbdrives ]]; then
		dunstify " Udisks2" "No USB drive detected"
		pkill -u "$USER" -x rofi
		exit
	else
		echo -en "\0prompt\x1fMount\n"
		echo "$usbdrives"
	fi
}

if [[ -z "$@" ]]; then
	rofi_list_drives
else
	chosen="$(echo -e "$1" | awk '{print $1}')"
	if [[ ! -z $chosen ]]; then
		mp=`udisksctl mount -b $chosen | rev | cut -d'/' -f1 | rev`
		dunstify " Udisks2" "$chosen mounted at /media/$mp"
	fi
	exit 0
fi

