#!/bin/sh

# A rofi prompt to unmount drives.
# Provides you with mounted partitions, select one to unmount.
# Drives mounted at /, /boot and /home will not be options to unmount.

function rofi_list_mounted_drives() {
	local drives=$(lsblk -nrpo "name,type,size,mountpoint" | awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$1,$3}')
	if [[ -z $drives ]]; then
		dunstify " Udisks2" "No drives to unmount"
		pkill -u "$USER" -x rofi
		exit
	else
		echo -en "\0prompt\x1fUnmount\n"
		echo "$drives"
	fi
}


if [[ -z "$@" ]]; then
	rofi_list_mounted_drives
else
	chosen="$(echo -e "$1" | awk '{print $1}')"
	if [[ ! -z $chosen ]]; then
		udisksctl unmount -b "$chosen" 1> /dev/null
		dunstify " Udisks2" "$chosen unmounted"
		exit 0
	fi
	exit 1
fi
