# ===================================================================
# == UI & Previews
# ===================================================================

# Enable image previews using your terminal's Sixel support
set preview_images true
set preview_images_method sixel

set preview_script ~/.config/ranger/scope.sh
set use_preview_script true

# Enable glyphs
# Requires devicons plugin
default_linemode devicons

# Disable mouse input to keep navigation strictly keyboard-focused
set mouse_enabled false

# ===================================================================
# == System & Behavior
# ===================================================================

# Enable Version Control System (VCS) integration to show git status
set vcs_aware true
set vcs_backend_git enabled

# ===================================================================
# == Custom Keybindings
# ===================================================================

# Filter as you type (Overrides the default 'f' find command)
map f console scout -ftsea%space

# Extract archives using our custom python plugin
map e console extract
