term=foot

font=monospace:size=10.0
bold-text-in-bright=no

# [window.padding] equivalent
pad=4x4
locked-title=yes

[colors-dark]
# moonlight.toml equivalent
background=212337
foreground=dce2f5

# Normal colors
regular0=131421  # black
regular1=ff757f  # red
regular2=2df4c0  # green
regular3=ffc777  # yellow
regular4=4f99ff  # blue
regular5=c4a2ff  # magenta
regular6=04dff9  # cyan
regular7=e4f3fa  # white

# Bright colors
bright0=363645   # bright black
bright1=f67f81   # bright red
bright2=6bf1ce   # bright green
bright3=ffdca9   # bright yellow
bright4=86b0ea   # bright blue
bright5=d6ccff   # bright magenta
bright6=41cfd9   # bright cyan
bright7=8585bb   # bright white

[csd]
# [window.decorations = "None"] equivalent
# Tells foot not to draw Client Side Decorations
preferred=none

[url]
# [[hints.enabled]] equivalent
# Foot has built-in URL parsing that matches your regex perfectly.
launch=xdg-open ${url}

[key-bindings]
# Maps Alt+F to trigger URL hints (like Alacritty's 'hints' mode)
show-urls-launch=Mod1+f

[text-bindings]
\x1b[108;6u = Control+Shift+l
\x1b[104;6u = Control+Shift+h
\x1b[107;6u = Control+Shift+k
\x1b[106;6u = Control+Shift+j
