#!/run/current-system/sw/bin/bash

# alacritty --config-file $XDG_CONFIG_HOME/alacritty/neomutt.toml -T "neomutt"
# wezterm --config-file $XDG_CONFIG_HOME/wezterm/neomutt.lua start --class neomuttTerm 
foot -c $XDG_CONFIG_HOME/foot/neomutt.ini

