hl.on( "hyprland.start", function ()
	hl.exec_cmd("hyprmoncfgd")
	hl.exec_cmd("noctalia")
	hl.exec_cmd("slack")
	hl.exec_cmd("neomutt-solo")
	hl.exec_cmd("vesktop")
	hl.exec_cmd("signal-desktop")
	hl.exec_cmd("hypridle")
end)
