general {
	lock_cmd = pidof hyprlock || hyprlock
	before_sleep_cmd = loginctl lock-session
	ignore_dbus_inhibit = false
}

listener { # Turns screen off in 3 minutes if locked
	timeout = 180
	on-timeout = pidof hyprlock && hyprctl dispatch dpms off
	on-resume = pidof hyprlock && hyprctl dispatch dpms on
}

listener { # Turns screen off in 10 minutes
	timeout = 600
	on-timeout = hyprctl dispatch dpms off
	on-resume = hyprctl dispatch dpms on
}

listener { # Lock screen after 15 minutes
	timeout = 900
	on-timeout = loginctl lock-session
}

listener { # Suspend system after 30 minutes unless on AC power
	timeout = 1800
	on-timeout = sh -c "systemd-ac-power || sudo systemctl suspend-then-hibernate"
}
