-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BOE 0x095F",
  mode = "2256x1504@60.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Dell Inc. DELL S2715H V14F3752485L",
  mode = "1920x1080@60.00",
  position = "2256x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:Dell Inc. DELL S2715H V14F3752528L",
  mode = "1920x1080@60.00",
  position = "4176x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
